name = 'fluidity'
license = 'MIT'
licenselink = 'https://github.com/wayjam/hugo-theme-fluidity/blob/master/LICENSE'
description = 'A fluid and responsive Hugo theme.'
homepage = 'https://github.com/wayjam/hugo-theme-fluidity'
demositev = "https://wayjam.github.io/hugo-theme-fluidity"
tags = ["blog", "fluent", "clean", "simple", "light", "dark" ,"writing", "syntax highlighting", "archives", "tailwindcss", "search", "emoji", "math typesetting", "fluent-design"]
features = ["blog", "responsive", "social media", "archives"]
[author]
  name = 'WayJam So'
  homepage = 'https://github.com/wayjam'
[module]
  [module.hugoVersion]
    min = "0.128.0"
